apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-authn
  namespace: kube-system
  labels:
    app: authn-webhook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authn-webhook
  template:
    metadata:
      labels:
        app: authn-webhook
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: authn-webhook
          image: victorbecerra/authn-webhook:v0.1
          imagePullPolicy: Always
          command:
            - /usr/local/bin/auth-webhook
            - --tls-cert-file=/certs/cert.pem
            - --tls-private-key-file=/certs/key.pem
          volumeMounts:
            - name: certs-volume
              mountPath: /certs
              readOnly: true
      volumes:
        - name: certs-volume
          secret:
            secretName: authn-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: my-authn
  namespace: kube-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: authn-webhook
---
apiVersion: v1
kind: Secret
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVV3RQSkFxdGs5cGJVd0NNVUZLU3gveWdpcWxRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0l6RWhNQjhHQTFVRUF3d1liWGt0WVhWMGFHNHVhM1ZpWlMxemVYTjBaVzB1YzNaak1CNFhEVEkxTURjdwpOekV3TVRjeE9Wb1hEVEkxTURnd05qRXdNVGN4T1Zvd0l6RWhNQjhHQTFVRUF3d1liWGt0WVhWMGFHNHVhM1ZpClpTMXplWE4wWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZ6OW0Kb0dHUnYrdXVzWndjMWFhdTRkcUxHMEExYlZDTnRWY0ZUVDNHZWcvdTJZb2RueTFYOEpaRmdnOS8vaHY5QW1aYgpMbmFZSFptTjBmeERTNkVFakZZajIvSTFSWmFNbU9EaGphSEZQajgvR01ldXBpS0dGREh1VzRrbE5kZ0pTV2RICmp1WnVDN3JsbzVkZGdUNGtnTW1MWFRtVkdGSWxLWGVGdlZUclJXVDVFOGhIdkRTd0ZPeTdHdWVOSnlJZlcwYTkKamRSdlp5NFBpeXdvdWlaaTJXa3laYnR6SWZHaWxVMGlCNnVCaUhqeEJWNUo2aEVHUTg1S05TbW4rdTlzT3pYcApJQnRIOTRhQU5QUFhaKzdzMkFvdEFhNWdTcUt3cjliT1FZcFFnNWRVL1RSYUFqRElCZGx1UlBLVW5hRkZCb0loClErbHYwbDJLT2t6Yy9Pcy9ld0lEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVWUZlUGE2ajlGZDczd21ERjlxSGUKaEswZDhuOHdId1lEVlIwakJCZ3dGb0FVWUZlUGE2ajlGZDczd21ERjlxSGVoSzBkOG44d0R3WURWUjBUQVFILwpCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFIeDBOTWx3cm14NnJ6ZUFEREhxTkVIbUMrcG1xCmNqaFpQZDRTU0RpZjRLZDAycGdhSzNGQjVSWXdTWnFST2VZc0VxOVFzZmdyMXladzRFc3IwZFRXbE5aR25oMjgKeHc4WFByOTkrdm1BY3VvelgzaWtBZTM1N3F2QUYzSk4ybTJTTFFHZS85RDVxT3Z4c1VSbzlBNUNSY3FWU1JDUApuK0dHbWxQSjhJd3hacVlWd010NE1LUWxHUDF5V0Y4TDFCdm5ockdDZWh1RTNKY25rc0IwTitFY2JVS0h0RmtECjY3cHBRR2t2UmYvWXBBcVVFZkVaOHlYbStYeU5VMmxEcEVXMlhyb1hEc2hMV0l0c24vQ25IaXhFRVc2d1VWL2MKMWw2KzVMRXl3Vkg5Y2lOKzRLVmNSa0tBVFA0OElBZHRrSlNEYlNDYkx0VXprbmgyMHhqTjV6a2d1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQy9QMmFnWVpHLzY2NngKbkJ6VnBxN2gyb3NiUURWdFVJMjFWd1ZOUGNaNkQrN1ppaDJmTFZmd2xrV0NEMy8rRy8wQ1psc3VkcGdkbVkzUgovRU5Mb1FTTVZpUGI4alZGbG95WTRPR05vY1UrUHo4WXg2Nm1Jb1lVTWU1YmlTVTEyQWxKWjBlTzVtNEx1dVdqCmwxMkJQaVNBeVl0ZE9aVVlVaVVwZDRXOVZPdEZaUGtUeUVlOE5MQVU3THNhNTQwbkloOWJScjJOMUc5bkxnK0wKTENpNkptTFphVEpsdTNNaDhhS1ZUU0lIcTRHSWVQRUZYa25xRVFaRHprbzFLYWY2NzJ3N05la2dHMGYzaG9BMAo4OWRuN3V6WUNpMEJybUJLb3JDdjFzNUJpbENEbDFUOU5Gb0NNTWdGMlc1RThwU2RvVVVHZ2lGRDZXL1NYWW82ClROejg2ejk3QWdNQkFBRUNnZ0VBQ0I5cHZQTVg3U1pWNzU0NVRVdThqc1FvOTFuVlN4VEtTQUx2cXpXdCtkNDIKWDAveDdTSlFZMXdHakwwYXl4Q21RTlZYRnhTYlpscHd2eFB2U2NXSGUyeG5MbjdOaTJ5WEFTRkFBek4xUEswVQpBWG50clltMjF5Rzl4VzZBUVphdzRraThMZElVcDNQakwvME1VQ0p6QzNORDg0d3dERzNrdlN1aDV3WTF6ZWNtCmw0SUxBbEhJQ2tQRk1yZUxvSjd0bDhRMk05eVZwMU5iOTgrZjBTa1IxYUFWRlJGUkNwT2t1Qk1HSFdCc29Pdm4KWDJiVmZ4TXNJS252bktHOHpVSEZ2K01oWWZMUDQ4MDB3NnNLVlJTN2t6SkIydUpuVFM1OVUwWEFLaHBISlNpZgpqS2J6OHMraFhZcUIxY29RRlFZTlk4U0VEWG95UGV1Y1lEYU82U21aM1FLQmdRRDBiYXBRSGZFSWxkSXBINW5kClVCbE92UW54MmpGdFJUYVp2TFpZRTBBRktYeGtqdGlLc1RiMUxaTWR6QVpBNVZFTFFxLzQzR2NRcnQ4TEdkdHQKYjIxYnBmMy9SeHZGeFQza2VQajEwbjNadTcrNVB2cHJOWit0RXJyZUFkclhiWFJ2Q3lFRXh6bnhrWDhoUlYzTQpuOTlqVmVPemhHV0F6S0NYWUpncDBBck41d0tCZ1FESVRUY1MycW1HU25mVTcvZjhFWG9DME81a3g2andaQUFVCkVuYkUyb0Y1aVU0Vy9QaXg2V0NvTUZhSWN5VnB0MkxxWUh1K0FEaCt1WlEzWC9tMndHNG5EaFFvZU9xODlJUSsKdzM1YVlEc1MxMVFPOHFST0pkRE1MV2RuOWtDVWFGVlRMbWh4UWM4TFVtR2ZzdGRWYnhsQzl4OTYyc01CWEJ5cApxSFl4ekdZSFRRS0JnRjU4ZmhmV1d6U01aZDlMdmZqVlc5TWFORnZ2a3FmQTE2aDZVS3FmVm1Jb2RWT1IvSmN3CmhpUWs1L2ZleEpRVmtVeWZETk5Rcis2OUNxK0o0VTdlZ2hHcGl4UkJjclR5MkVnWGszWERWcTd5YXR5N1FhWnIKNWp2TFA3MU9Ua0IwcVV1N3E1bmpRYnptRjVUTzhjR0dFNTZjdHhiUUdVUysxVjF2RTZNbUx1Y0ZBb0dBYXJ1SwpmMGQ1VWcvWWJ1VTROVjl5cnBGNmxzVTFwbk1DLzY4ZkRxS0luNlNrc2VjMjlrYXZ0SytkVExSZTJVaFpNeDhhCmtSSTVDSDRIRnNMVG82aENpaGtjY0x5T0NRWWFlZjllRXZaNFEvL3QwTkZHOEVXQ1QycGFVYkdNbEFoTWZ6aVoKZXRCZ2JWNEdtenlITmdVdlp0bWNNckRqZkpRQ3lmejBqbkNtWlhrQ2dZQWlhcGZTQU1uVkpvMVMwNmxXdFE1aApKaXQ4Z1NhZy9na1NldVdiRzVEVG0vKzBCd1BmN2JMQVptLzk5cmo4UkZvQlQ0TEVyOCtCZFU3TWVSeENLSXlmCmxJQVVTcFRzVCtGSVQ5VEs3T0lPL0hkdzRmVldUY1ptN2NqUHU2QnlOVm5paEVMcXJUZXpGSVFxRmU5K3l5enEKWEZpb2hmd2h4dStYeDQrZ2ZaZjFQZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
metadata:
  name: authn-webhook-certs
  namespace: kube-system
type: Opaque
