apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-authz
  namespace: kube-system
  labels:
    app: authz-webhook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authz-webhook
  template:
    metadata:
      labels:
        app: authz-webhook
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: authz-webhook
          image: victorbecerra/authz-webhook:v0.1
          imagePullPolicy: Always
          command:
            - /usr/local/bin/authz-webhook
            - --tls-cert-file=/certs/cert.pem
            - --tls-private-key-file=/certs/key.pem
          volumeMounts:
            - name: certs-volume
              mountPath: /certs
              readOnly: true
      volumes:
        - name: certs-volume
          secret:
            secretName: authz-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: my-authz
  namespace: kube-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: authz-webhook
---
apiVersion: v1
kind: Secret
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVZlR1R055akdsTC8xUFZWRjF6QURQNWV6R21rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0l6RWhNQjhHQTFVRUF3d1liWGt0WVhWMGFIb3VhM1ZpWlMxemVYTjBaVzB1YzNaak1CNFhEVEkxTURjdwpPREV6TURjMU5sb1hEVEkxTURnd056RXpNRGMxTmxvd0l6RWhNQjhHQTFVRUF3d1liWGt0WVhWMGFIb3VhM1ZpClpTMXplWE4wWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTBmMXIKS3BaTitDcXFycUNPSit2SmpKTExEWFo1aFZwU3huelpNdjFCNlE2cS93a05GS1lwS1U0M0hsUmhwMUlIM3VabQpkQnZzdXlYMktqYXFBeCt2ZndUTUJMUXBpVjNyN2ZSQXAzTytDL2dxWGI5N1FNUGtoY1FlcW1xNEx1QWRTUzJ2CmlURnNpMFB1NGhEb1dMa2d1SjI3UXVsRzI5VGh0TDlrMzhIdGVJQytjRnhrazArNmNQeG82VktuVXFCaWNEck4KL1pVU1VYNURSbDF0eGNPYWhYekxZZTFLNzduVmsrZTdvc2ZkRkxDQnhxTEt6NHNJcncwNTFEUEd3RFl6TElFTQpBYkgxZEJ6ekt2UDhWdXp6OVY0TS9ONUQ2YTFUSnVvekNJVll3QmNzb0ZudTh2MVNBS1JoWWYxVDA5dHFVbC9ECnVaMklVYTU4UDVmOTBMRzdmUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVVXh5YzRjZWRwRlM0NW9TenkwOUcKQU1QWGhXa3dId1lEVlIwakJCZ3dGb0FVVXh5YzRjZWRwRlM0NW9TenkwOUdBTVBYaFdrd0R3WURWUjBUQVFILwpCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqVEpGbVE4OEVGRmJ1SFRIQ3h5RENhNUFwYWd5CmhuMUt6Z2xMUUNtS1NvL3doazl6Q3c2eFpxWU5LcVo4MFZHT1FmbEt1bEdWa2ZVT3hRUGdWWUI0RmF0UHNuUlQKVEZ5YXoyYnpGSERCVWhTTU1naC9VUXNiYXlNSEZzVXNIYTNXSDk0UHlURkR6VlV4ZlVYVFRJODZEYUdXZmx0Qgp0cUUvb2tSelhHNGt5MW40allRSllIQWJQUjA4aFBDYUpXemJhK2FTN3ZSOTR3VzFQbW4xblFvMkx0b2xySVdUClFXZFFaZjZPb2xGU3E2ZGZyVGRadGFVRlArUW5mU2NhVE9hOUU2M2ZpY09oRmc2OXlYakNsRHhYeFZCU2V0NisKaXF5QW9La2NOWUZFQk9JQU05aTNkZzVyc2JHYlZFOFlNNHpYS0pWZnJrUHNkYmlFVjc5UitUZGdxQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFIvV3NxbGszNEtxcXUKb0k0bjY4bU1rc3NOZG5tRldsTEdmTmt5L1VIcERxci9DUTBVcGlrcFRqY2VWR0duVWdmZTVtWjBHK3k3SmZZcQpOcW9ESDY5L0JNd0V0Q21KWGV2dDlFQ25jNzRMK0NwZHYzdEF3K1NGeEI2cWFyZ3U0QjFKTGErSk1XeUxRKzdpCkVPaFl1U0M0bmJ0QzZVYmIxT0cwdjJUZndlMTRnTDV3WEdTVFQ3cHcvR2pwVXFkU29HSndPczM5bFJKUmZrTkcKWFczRnc1cUZmTXRoN1VydnVkV1Q1N3VpeDkwVXNJSEdvc3JQaXdpdkRUblVNOGJBTmpNc2dRd0JzZlYwSFBNcQo4L3hXN1BQMVhnejgza1BwclZNbTZqTUloVmpBRnl5Z1dlN3kvVklBcEdGaC9WUFQyMnBTWDhPNW5ZaFJybncvCmwvM1FzYnQ5QWdNQkFBRUNnZ0VBQlFZSUtzclJaRnhNOGdReThtbmdkcVdmc3ZEckk2YTZCVGZydXZNTHdSeTgKallFS0dEemVEamdVb2RGSW9YS1pHcHJZeDUxUUVxMXIrcTJOR3FteGpwc3U4RXZlYWRsZWhyWkpyUUtHcTQyaQpkeW9EWGxUR3Q1dllxZllIU3ZrZlA1RnNEM1JURVpxQjhWUTdPQkxSdHI1RjdSU3g2OFM4MDVDaW1WSEZNYi91ClM4YnRrd1JhS202ZHRmQUpBTWlEdnp1Z0JOKzBiSTF5SFVKQVNLN25JdEw2T29SazB3dk5QZjUvajlKQTBkZWUKa2VjWkxwaDcyRnZIU0d1Wit6RzVON2s1NDRSc01ZbTJ1WnVHZE45a2swTHNKK3E0S0lmZXY4WUh3amQ5U2J2MgpsWDc5NWprU3hoeERnQjRMeEttdWVpRyt0M0hPWUJxeTFoU2VFaC8vd1FLQmdRRG40THUrMG5qemVVdmVidnhDCjhSSzRrM0UrVmJkMHdySE85WHZZcTQ1bWxwTzFrV3htdnlBS0VHdjZSY3c3TTI4Y2Y0OHg4ZWl4SFE2Z0o3RGEKeE50NHRjUitnbkxwZVBtbmFKS3dYd1c0QjZNaUROMUpJY1VaTCtJOFZrY2IzaVlyazQzVnFXN2g1dzZuSnZoQgpDSkhOak9qUENGOXVvZWhabUtDcU0wZE9vUUtCZ1FEbjFjWjR3Q3V1ZTY5UitTcis3amZ2YUZ4SXJxL2YrTXBVCjU3SFhyWkV3RHh6eU1VaHI0elllUnQzRkxPWXhMQXlCb1hyKzRzQWZwUDh0Qi83c2dVdGQ4aFFidXg3RG1VclMKWTBnUElwSmoybSthZmh0NU9zeVBDZnNQSHdEWHZ6UHMzVEFnWWR6ZVZ4VDJBdXkxWTdoWmdJempQcDFMMnpIdwpWOEVlaVNGTFhRS0JnUUNYVkRqVE1hTlVLdDVUM1pUdXoweExmNVpSZXptT2p4M2lGcDNyNnhLMWF5SWRSam83CjJCSTkzemZKRDFKWmRKallQWHVqdWVBRjd4UERmQVBVMHRMMU5aTjJpUVlienlNSG1aemFWRGwwUUMrOElpOHMKOGtnaXh2aGNMbWFjRG1CVTRpaVh2OHNvelZYbnl1d0w3VjdTaWxySit3bmxOdTlmd2RkaEhMUTE0UUtCZ0RZZgpqa282Y3ZnMUgrVC9TcTVoWnVXWmM1SDBWbEx2Zml6OE9tU2p2TFYva2I1cEN3TkU5Q2wxV2VqaVpvc3NRVzh5CkI4amhud0RFUUY1KzgyQzdmcURjRngyeVBhaGtiVGRZdmtYcVNFclBnQ2FOTWxUSENXS0xiZlZGdzZpYWxzREIKa3E2OHFoZXVOTktLTkVEVW13RXFKYm9Yc0JrNWZ4c2hJWkREYXVaeEFvR0FhU3lCYTlJWnpPUEVzZ1o0SWZXdgpkQ2lMYkNEcVNNcWprdGNuK1NyWjBJUGhacGJyQ0xYazVncm90aWY1SjNnY29FMkdjMlJRcjlKazVlU3UwZENUCmJDT2ZCRUprSktORzZ4TWJMWTJRNER1Y3hwd0dFWllxU2FZanlZa250T1EzL0FuUTh6akI1bzlER1NScXVUWGUKY1Q1Zy9KN3ZBYk13WlBPbFNDRzQxKzA9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
metadata:
  name: authz-webhook-certs
  namespace: kube-system
type: Opaque
